<?php

/**
 * @file
 * Implements configurable social network share links to nodes
 */

/**
 * Implements hook_menu().
 */
function custom_social_share_menu() {
  $items = array();
  $items['admin/config/content/custom-social-share'] = array(
    'title'            => 'Custom Social Share',
    'description'      => 'Configure share link styling.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('custom_social_share_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'custom_social_share.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_node_view().
 */
function custom_social_share_node_view($node, $view_mode, $language) {
  // these three lines check to see if we can display the share box
  if (($view_mode == 'teaser' && variable_get('custom_social_share_teaser', 1)) || ($view_mode == 'full')) {
    $enabledTypes = variable_get('custom_social_share_node_types', array());
    if (isset($enabledTypes[$node->type]) && ($enabledTypes[$node->type])) {

      // get a list of enabled share links and generate them individually
      $sites = variable_get('custom_social_share_sites', array());
      foreach ($sites as $site => $enabled) {
        if ($enabled) {
          $node->content['custom_social_share'][] = _custom_social_share_link($site, $node);
        }
      }
      // put the shareBox into the node before it's rendered
      $suffix = (variable_get('custom_social_share_label') == '') ? '' : ': ';
      $node->content['custom_social_share']['#weight'] = variable_get('custom_social_share_weight', 0);
      //$node->content['custom_social_share']['#prefix'] = '<div class="social-share"><span>'. variable_get('custom_social_share_label', 'Share to') . $suffix .'</span>';
      //$node->content['custom_social_share']['#suffix'] = '</div>';
    }
  }
}

function _custom_social_share_link($site, $node) {
  global $base_url;
  static $i = 1;
  
  // define the share links
  $sites['facebook']   = array('name' => 'Facebook', 'url' => 'http://facebook.com/sharer.php?u=%URL%&amp;t=%TITLE%');
  
  $sites['vkontakte']   = array('name' => t('Vkontakte'),'icon'=>'vk16.png' , 'url' => 'http://vkontakte.ru/share.php?url=%URL%&title=%TITLE%&description=%DESC%');
  if (variable_get('custom_social_share_twitter_method', 'original') == 'original') {
    $sites['twitter']  = array('name' => 'Twitter', 'icon'=>'twitter16.png', 'url' => 'http://twitter.com/status?=%TITLE%+%URL%');
  }
  else {
    $sites['twitter']  = array('name' => 'Twitter', 'icon'=>'twitter16.png', 'url' => 'http://twitter.com/intent/tweet?url=%URL%&amp;text=%TITLE%');
  }
  $sites['googlebuzz'] = array('name' => 'Google Buzz', 'url' => 'http://www.google.com/buzz/post?url=%URL%&amp;message=%TITLE%');
  $sites['myspace']    = array('name' => 'Myspace', 'url' => 'http://www.myspace.com/Modules/PostTo/Pages/default.aspx?u=%URL%&amp;c=%TITLE%');
  $sites['msnlive']    = array('name' => 'MSN Live', 'url' => 'http://profile.live.com/badge/?url=%URL%&amp;title=%TITLE%&amp;description=%DESC%');
  $sites['yahoo']      = array('name' => 'Yahoo', 'url' => 'http://bookmarks.yahoo.com/toolbar/savebm?opener=tb&amp;u=%URL%&amp;t=%TITLE%&amp;d=%DESC%');
  $sites['linkedin']   = array('name' => 'LinkedIn', 'url' => 'http://www.linkedin.com/shareArticle?url=%URL%&amp;mini=true&amp;title=%TITLE%&amp;ro=false&amp;summary=%DESC%&amp;source=');
  $sites['orkut']      = array('name' => 'Orkut', 'url' => 'http://promote.orkut.com/preview?nt=orkut.com&amp;tt=%TITLE%&amp;du=%URL%&amp;cn=%DESC%');
  $sites['digg']       = array('name' => 'Digg', 'url' => 'http://digg.com/share?url=%URL%&amp;title=%TITLE%');
  $sites['delicious']   = array('name' => 'Delicious', 'url' => 'http://www.delicious.com/save?v=5&amp;noui&amp;jump=close&amp;url=%URL%&amp;title=%TITLE%');
  
  // check for an alias on the node
  if (!isset($node->link)) {
    $row = db_query("SELECT alias FROM {url_alias} WHERE source = :src", array(':src' => 'node/'. $node->nid));
    $alias = $row->fetchColumn();
    $url = $base_url .'/'. ($alias ? $alias : 'node/'. $node->nid);
  }
  else {
    $url = $node->link;
  }

  // if the shorten_urls module is installed & enabled, shorten the url being shared.
  if (module_exists('shorten')) {
    $url = shorten_url($url);
  }

  // switch out placeholders with node information
  $maxDescLength = variable_get('custom_social_share_max_desc_length', 50);
  $target = variable_get('custom_social_share_target', 0);

  $placeholders = array(
    '%TITLE%',
    '%URL%',
    '%DESC%'
  );

  if (isset($node->nid)) {
    $body = field_get_items('node', $node, 'body');
    if (!empty($body) && $body[0]['format'] == 'php_code') {
      $body = $body[0]['value'];
    }
    else {
      $body = (!empty($body) && isset($body[0]['safe_value'])) ? $body[0]['safe_value'] : '';
    }
  }
  else {
    $body = '';
  }

  // Trim title so it will fit in a tweet.
  if ($site == 'twitter' && variable_get('custom_social_share_twitter_truncate', 0)) {
    if ((strlen($url) + strlen($node->title)) > 140) {
      $length = 136 - strlen($url);
      $title  = substr($node->title, 0, $length);
      $title .= '...';
    }
  }

  if (!isset($title) || $title == '') {
    $title = $node->title;
  }

  $replacements = array(
    urlencode($title),
    $url,
    urlencode(strip_tags(strlen($body) > $maxDescLength ? substr($body, 0, $maxDescLength) .'...' : $body))
  );

  $options = array('html'=>true, 'attributes' => array('class' => 'social-share-'. $site));
  if (variable_get('custom_social_share_new_window', 0)) {
    $options['attributes']['target'] = '_blank';
  }
  $link = array(
    '#type'    => 'link',
    '#html'    => 'html',
    '#title'   => $sites[$site]['name'],
    '#href'    => str_replace($placeholders, $replacements, $sites[$site]['url']),
    '#options' => $options,
    '#suffix'  => '</span> ',
    '#prefix'  => '<span class="icon icon'.$i++.'">',
  );
  if(isset($sites[$site]['icon']))
    $link['#title'] = '<img src="/'.drupal_get_path('theme','fc_arsenal_theme').'/img/icons/'.$sites[$site]['icon'].'">'; 
  // Return the link
  return $link;
}

/**
 * Implements hook_block_info().
 */
function custom_social_share_block_info() {
  $blocks = array();
  if (variable_get('custom_social_share_block', 0)) {
    $blocks['custom_social_share'] = array(
      'info'       => t('Social Share'),
      'visibility' => 1,
      'status'     =>TRUE,
      'region'     => 'header',
      'weight'     => 0,
    );
  }
  
  $blocks['social_share_links'] = array(
      'info'       => t('Social Share Links'),
      'visibility' => 1,
      'status'     =>TRUE,
      'region'     => 'header',
      'weight'     => 0,
    );
    
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function custom_social_share_block_view($delta = '') {

  // This example comes from node.module. Note that you can also return a
  // renderable array rather than rendered HTML for 'content'.
  $block = array();
  
  if($delta == 'social_share_links'){
    $block['content'] = '<ul class="header-social-links">';
    $block['content'] .= '<li class="header-social-link-item header-vk-link">'.theme('custom_social_share_vk_header_link').'</li>';  
    $block['content'] .= '<li class="header-social-link-item header-twitter-link">'.theme('custom_social_share_twitter_header_link').'</li>';  
    $block['content'] .= '<li class="header-social-link-item header-fb-link">'.theme('custom_social_share_facebook_header_link').'</li>';  
    $block['content'] .= '<li class="header-social-link-item header-mail-link">'.theme('custom_social_share_email_link').'</li>';  
    $block['content'] .= '</ul>'; 
  }
  
  if (user_access('access content') && variable_get('custom_social_share_block', 0)) {
    $block['subject'] = t('Social Share');
      $sites = variable_get('custom_social_share_sites', array());
      $node = (object)node_load(arg(1));
      if (!isset($node->nid)) {
        $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
        $node->link = url($path, array('absolute' => TRUE));
      }
      if (!isset($node->title)) {
        $node->title = variable_get('site_name', "");
      }
      foreach ($sites as $site => $enabled) {
        if ($enabled) {
          $block['content']['custom_social_share'][] = _custom_social_share_link($site, $node);
        }
      }
  }
  return $block;
}


function custom_social_share_theme(){
  return array(
    'custom_social_share_vk_link'=>array('variables'=>NULL),
    'custom_social_share_twitter_link'=>array('variables'=>NULL),
    'custom_social_share_facebook_link'=>array('variables'=>NULL),
    'custom_social_share_email_link'=>array('variables'=>NULL),
    'custom_social_share_twitter_header_link'=>array('variables'=>NULL),
    'custom_social_share_facebook_header_link'=>array('variables'=>NULL),
    'custom_social_share_vk_header_link'=>array('variables'=>NULL),
  
  );

}

function theme_custom_social_share_vk_link($variables){
  return theme_link(array('path'=>'http://vkontakte.ru/share.php?url='.urlencode('http://fc-arsenal.com').'&title='.urlencode(variable_get('site_name','')),'text'=>theme_image(array('path'=>drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/vk.gif','attributes'=>array())), 'options'=>array('html'=>true,'attributes'=>array('target'=>'_blank'))));
}

function theme_custom_social_share_twitter_link($variables){
  return theme_link(array('path'=>'http://twitter.com/intent/tweet?url='.urlencode('http://fc-arsenal.com').'&text='.urlencode(variable_get('site_name','')),'text'=>theme_image(array('path'=>drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/twitter.gif','attributes'=>array())), 'options'=>array('html'=>true,'attributes'=>array('target'=>'_blank'))));
}

function theme_custom_social_share_facebook_link($variables){
  return theme_link(array('path'=>'http://facebook.com/arssc.moscow','text'=>theme_image(array('path'=>drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/facebook-icon.png','attributes'=>array())), 'options'=>array('html'=>true,'attributes'=>array('target'=>'_blank'))));
}

function theme_custom_social_share_vk_header_link($variables){
  return theme_link(array('path'=>'http://vk.com/arssc','text'=>theme_image(array('path'=>drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/vk.gif','attributes'=>array())), 'options'=>array('html'=>true,'attributes'=>array('target'=>'_blank'))));
}

function theme_custom_social_share_twitter_header_link($variables){
  return theme_link(array('path'=>'http://twitter.com/fc_arsenal_com','text'=>theme_image(array('path'=>drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/twitter.gif','attributes'=>array())), 'options'=>array('html'=>true,'attributes'=>array('target'=>'_blank'))));
}

function theme_custom_social_share_facebook_header_link($variables){
  return theme_link(array('path'=>'http://facebook.com/arssc','text'=>theme_image(array('path'=>drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/facebook-icon.png','attributes'=>array())), 'options'=>array('html'=>true,'attributes'=>array('target'=>'_blank'))));
}

function theme_custom_social_share_email_link($variables){
  return theme_link(array('path'=>'mailto:admin@fc-arsenal.com','text'=>theme_image(array('path'=>drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/mailLink.gif','attributes'=>array())), 'options'=>array('html'=>true,'attributes'=>array())));
}