<?php
function mobile_version_menu(){
  $items = array();
  
  $items['mobile/get_news_list']=array(
    'type'=>MENU_CALLBACK,
    'page callback' => 'mobile_version_get_news_list',
    'access callback' => TRUE
  );
  
  $items['mobile/get_news_item/%']=array(
    'type'=>MENU_CALLBACK,
    'page callback' => 'mobile_version_get_news_item',
    'page arguments' => array(2),
    'access callback' => TRUE
  );
  
  $items['mobile/get_calendar']=array(
    'type'=>MENU_CALLBACK,
    'page callback' => 'mobile_version_get_calendar',
    'access callback' => TRUE
  );
  
  return $items;
  
}


function mobile_version_get_news_list(){
  $view = views_get_view('news');
  $view->set_display('news_by_category');
  $view->execute('news_by_category');
  $news = array();
  foreach($view->result as $news_item){
    $news[] = array(
      'nid'=>$news_item->nid,
      'title'=>$news_item->node_title,
      'summary'=>strip_tags($news_item->field_body[0]['rendered']['#markup']),
    );
  }
  drupal_json_output($news);
}

function mobile_version_get_news_item($nid = null){
  if(empty($nid)) 
    die();
  
  $node = node_load($nid);
  if(empty($node)) 
    die();

  $info = array(
    'title' => $node->title,
    'body' => check_markup($node->body[$node->language][0]['safe_value'],'full_html')
              .'<br /><br /><a href="/" title="Вернуться к списку новостей">Вернуться к списку новостей</a>'
  );
  drupal_json_output($info);
  
}

function mobile_version_get_calendar(){

  $view = views_get_view('matches');
  $view->set_display('next_5_matches');
  $view->execute('next_5_matches');
 
  
  
  $next_match_html = '<b>'.t('Next 5 matches').'</b>:<br /> ';
  if(!empty($view->result)){
    foreach($view->result as $res){
    //$next_match_info = $res[0];

    $month_names_genitive = variable_get('month_names_genitive',array());
    $match_timestamp = strtotime($res->field_data_field_match_start_date_field_match_start_date_val) + date('Z');
    $month = date('m',$match_timestamp);
    $match_start_date = format_date($match_timestamp,'custom','l, j ').(isset($month_names_genitive[$month]) ? $month_names_genitive[$month]  : date('F',$match_timestamp)).date(' H:i',$match_timestamp);
    
    $next_match_html .= l($res->node_title,
                          'node/'.$res->nid,
                          array('absolute'=>true)
                          )
                      .', '.$match_start_date.' '.t('moscow_time_short')
                      .'<br />';
                      ;
    }
  }
 // print_r($next_match_info);
 // die();
  
  
  $view = views_get_view('matches');
  $view->set_display('prev_match');
  $view->execute('prev_match');
  $prev_match_html = '';
  if(!empty($view->result)){
    $prev_match_info = $view->result[0];
    
    $month_names_genitive = variable_get('month_names_genitive',array());
    $match_timestamp = strtotime($prev_match_info->field_field_match_start_date[0]['raw']['value']) + date('Z');
    $month = date('m',$match_timestamp);
    $match_start_date = format_date($match_timestamp,'custom','l, j ').(isset($month_names_genitive[$month]) ? $month_names_genitive[$month]  : date('F',$match_timestamp)).date(' H:i',$match_timestamp);
   
    $prev_match_html = '<b>'.t('Previous match').'</b>: '.
                                                 l(($prev_match_info->field_field_match_place[0]['raw']['value'] == 'away'  
                                                    ? $prev_match_info->field_field_match_opponent[0]['rendered']['#markup'].' '.$prev_match_info->field_field_match_result[0]['rendered']['#markup'].' '.t('Arsenal')
                                                    : t('Arsenal').' '.$prev_match_info->field_field_match_result[0]['rendered']['#markup'].' '.$prev_match_info->field_field_match_opponent[0]['rendered']['#markup']
                                                    ),
                                                'node/'.$prev_match_info->nid,
                                                array('absolute'=>true)
                                                )
                       .', '.$match_start_date.' '.t('moscow_time_short');                             
                                                  
  }
  
  $tournament_table_html = '<b>'.t('Tournament table').'</b>:<br /><div class="tournament_table_wrapper">';
  
  $tournament_table_html .= _get_tournament_table('short', null, null, 10).'</div>';
  //print_r($tournament_table);
  //die();
  /*$news = array();
  foreach($view->result as $news_item){
    $news[] = array(
      'nid'=>$news_item->nid,
      'title'=>$news_item->node_title,
      'summary'=>strip_tags($news_item->field_body[0]['rendered']['#markup']),
    );
  }
  drupal_json_output($news);*/
  $return = array(
    'prev_match_html' => $prev_match_html,
    'next_match_html' => $next_match_html,
    'tournament_table_html' => $tournament_table_html,
  );
  //print_r($return);
  drupal_json_output($return);
  die();


}
?>