<?php

function custom_match_menu(){
  $items = array();
  
  $items['get_next_match_ajax/%']= array(
    'type'=>MENU_CALLBACK,
    'page callback'=>'_get_next_match',
    'page arguments'=>array(1),
    'access callback' => TRUE
  );
  return $items;
}

function custom_match_theme(){
  return array(
  'custom_match_arsenal_logo_match_block'=> array(),
  'custom_match_simple_tabs'=> array('variables'=>array()),
  'custom_match_match_teaser'=> array('variables'=>array()),
  'custom_match_match_team_block'=> array('variables'=>array()),
  );
}

function _get_next_match($current_id){
  
  if((int)$current_id > 0)
  {
    $current_node = node_load($current_id);
    
    $next_id = db_query("
      SELECT sd.entity_id
      FROM {field_data_field_match_start_date} sd
      WHERE sd.field_match_start_date_value > :start_date 
      ORDER BY sd.field_match_start_date_value
      LIMIT 1 
    ",array(':start_date'=>$current_node->field_match_start_date[$current_node->language][0]['value']))->fetchField();
    if(!empty($next_id) && (int)$next_id > 0){
      $id = $next_id;
      $message = "OK";
    }
    else{
      $id = $current_id;
      $message = "LAST_MATCH";
    }
  }
  else{
    $id = $current_id;
    $message = "WRONG_PARAMETER";
  }
  
  $html = views_embed_view('matches','next_match',$id);
  $data = array('html'=>$html,'id'=>$id,'message'=>$message);  
  return drupal_json_output($data);
    
}

function theme_custom_match_arsenal_logo_match_block(){
  $image_uri = 'arsenal_logo_small.gif';  
  //$image_uri = drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/arsenal_logo_small.gif';  
//  die($image_uri);
  return theme('image_style', array('style_name' => 'team_logo_small', 'path' => $image_uri));
  //return theme('image', $path . '/' . FILENAME_ARSENAL_EMBLEM);
}

function custom_match_preprocess_views_view_fields(&$variables){
  $view = $variables['view'];
  if($view->name == 'matches' && ($view->current_display == 'last_match' || $view->current_display == 'next_match')){
    if($view->result[0]->field_field_match_place[0]['raw']['value'] == 'home'){
      $first_team_img = theme('custom_match_arsenal_logo_match_block');
      $first_team_name = t('Arsenal');
      $second_team_img = render($variables['fields']['field_team_logo']->content); 
      $second_team_name = render($variables['fields']['field_match_opponent']->content); 
    }
    else{
      $first_team_img = render($variables['fields']['field_team_logo']->content); 
      $first_team_name = render($variables['fields']['field_match_opponent']->content); 
      $second_team_img = theme('custom_match_arsenal_logo_match_block');
      $second_team_name = t('Arsenal');  
    }
    $variables['match']['teams']['first'] = array('img'=>$first_team_img, 'name'=>$first_team_name);
    $variables['match']['teams']['second'] = array('img'=>$second_team_img, 'name'=>$second_team_name);
    $month_names_genitive = variable_get('month_names_genitive',array());
    $match_timestamp = strtotime($view->result[0]->field_field_match_start_date[0]['raw']['value']);
    $month = date('m',$match_timestamp);
    $variables['match']['start_date'] =  format_date($match_timestamp,'custom','l, j ').(isset($month_names_genitive[$month]) ? $month_names_genitive[$month]  : date('F',$match_timestamp)).date(' h:i',$match_timestamp);
    
    $variables['match']['score'] = '';
    if(!empty($variables['fields']['field_match_result'])){
      $variables['match']['score'] = render($variables['fields']['field_match_result']->content);
    }
    
    $variables['additional_link'] = '';
    if($view->current_display == 'next_match'){
      $variables['additional_link'] = l(t('online'),'http://www.liveresult.ru/football/txt/team/arsenal',array('attributes'=>array('target'=>'_blank'),'absolute'=>TRUE));
    }
  }  
}

  
function _tab_divs($tabs, $div_css = '', $selected_number = 0, $css_suffix = '') {
  $html = "<div class='$div_css'>";
  if (is_array($tabs)) {  
    foreach ($tabs as $k=>$e) {
      $selected = ($selected_number == $k) ? 'tab-active' : '';
      $id = $k.$css_suffix;
      $html .= "<div id='$id' class='tab $selected'>$e</div>";
    }
  }
  $html .=  '<div class="cf"></div>'.
            '</div>';
  return $html;
}

function theme_custom_match_simple_tabs( $vars ) {   
  $headers = array_shift($vars);
  $content = array_shift($vars);
  $selected_number = array_shift($vars);
  
  $path = drupal_get_path('theme', variable_get('theme_default','fc_arsenal_theme'));
  drupal_add_js($path . '/js/custom.js');
  $html = '<div class="tabs">';
  if (is_array($headers)) {
    $html .= _tab_divs($headers, "header", $selected_number);
  }
  if (is_array($content)) {
    $html .= _tab_divs($content, "content", $selected_number, "content");
  }
  
  $html .= '</div>';
  return $html;
}

function theme_custom_match_match_teaser($vars=array()){
  $node = array_shift($vars);
  $title = array_shift($vars);
  //dpm($node);
  $output = '';
  //dd($node);
  $output .= '<div class="match-teaser">';
  //$output .= '<h2>'. (($title != '') ? $title : $node->title ) . '</h2>';
  $output .= '<h2>'.ucfirst(t('Match-centre')).'</h2>';
  
  $rival_nid = $node->field_match_opponent[$node->language][0]['nid'];
  $rival_node = node_load($rival_nid);
  if($rival_node->field_team_logo[$rival_node->language][0]['fid']){
    $rival_emblem = theme_image(array('attributes'=>array(), 'path'=> $rival_node->field_team_logo[$rival_node->language][0]['uri']));
  } else {
    $path = drupal_get_path('theme', variable_get('theme_default','fc_arsenal_theme'));
    $image_path = $path . '/no-photo.jpg';
    $rival_emblem = theme('image', array('attributes'=>array(), 'path'=>$image_path));
  }
  $arsenal_emblem = theme('custom_match_arsenal_logo_match_block');
  
  $rival_block = '
      <div class="team-block">
        <div class="emblems-line">'.$rival_emblem.'</div>
      </div>';
  $arsenal_block = '
      <div class="team-block">
        <div class="emblems-line">'.$arsenal_emblem.'</div>
      </div>';
  
  $result = '';
  if(!empty($node->field_match_result)) 
    $result = $node->field_match_result[$node->language][0]['safe_value'];
    
  if($node->field_match_place[$rival_node->language][0]['value'] == 'away'){
    $teaser_left = '<div class="players">'.$rival_block . '<div class="vs">VS</div>' . $arsenal_block . '<div class="cf">&nbsp;</div></div>';
    $teaser_right = '<div class="team-line">'.$rival_node->title.' - '.t('Arsenal').' '.$result.'</div>';
  } else {
    $teaser_left = '<div class="players">'.$arsenal_block . '<div class="vs">VS</div>' . $rival_block . '<div class="cf">&nbsp;</div></div>';
    $teaser_right = '<div class="team-line">'.t('Arsenal').' - '.$rival_node->title.' '.$result.'</div>';
  }
  
  $additional_info = '';
  
  
  if(!empty($node->field_match_season) && $node->field_match_season[$node->language][0]['taxonomy_term']){
    $additional_info .= '
    <div class="info">
      <span class="label">'.t('Season').': </span>
      <span class="value">'.$node->field_match_season[$node->language][0]['taxonomy_term']->name.'</span>
    </div>';
  }

  if(!empty($node->field_match_stadium) && $node->field_match_stadium[$node->language][0]['node']){
    $additional_info .= '
    <div class="info">
      <span class="label">'.t('Stadium').': </span>
      <span class="value">'.$node->field_match_stadium[$node->language][0]['node']->title.'</span>
    </div>';
  }
  
  if(!empty($node->field_match_round) && $node->field_match_round[$node->language][0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">'.t('Tournament round').': </span>
      <span class="value">'.$node->field_match_round[$node->language][0]['value'].'</span>
    </div>';
  }
  
  if(!empty($node->field_match_referee) && $node->field_match_referee[$node->language][0]['node']){
    $additional_info .= '
    <div class="info">
      <span class="label">'.t('Referee').': </span>
      <span class="value">'.$node->field_match_referee[$node->language][0]['node']->title.'</span>
    </div>';
  }
  
  if(!empty($node->field_match_attendance) && $node->field_match_attendance[$node->language][0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">'.t('Attendance').': </span>
      <span class="value">'.number_format($node->field_match_attendance[$node->language][0]['value'],0,'',' ').'</span>
    </div>';
  }
  
 /* if($node->field_goal_authors[0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">Авторы голов: </span>
      <span class="value">'.$node->field_goal_authors[0]['view'].'</span>
    </div>';
  }
  
  if($node->field_penalty_cards[0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">Жёлтые карточки: </span>
      <span class="value">'.$node->field_penalty_cards[0]['view'].'</span>
    </div>';
  }
  
  if($node->field_field_red_cards[0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">Удаления: </span>
      <span class="value">'.$node->field_field_red_cards[0]['view'].'</span>
    </div>';
  }
  if($node->field_additional_information_0[0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">Дополнительная информация: </span>
      <span class="value">'.$node->field_additional_information_0[0]['view'].'</span>
    </div>';
  }
      */
  //dd($node);
  
  /*if($node->field_gallery_id[0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="value">'.l('Галерея' , GALLERY_PAGE.'/'.$node->field_gallery_id[0]['value']).'</span>
    </div>';
  }*/
  
 
  $output .= '
<div class="teaser-content">
  <div class="teaser-left-part">
    '.$teaser_left.'
  </div>
  <div class="teaser-right-part">
    '.$teaser_right.'
    <div class="tournament">'.$node->field_match_tournament[$node->language][0]['taxonomy_term']->name.'</div>
    <div class="date">'.format_date(strtotime($node->field_match_start_date[$node->language][0]['value']),'short') .'</div>
  </div>
  <div class="cf">&nbsp;</div>
  <div class="additional-info">'.$additional_info.'</div>
</div>';
  //$node;
  
  $output .= '</div>';
  
  return $output;
}

function theme_custom_match_match_team_block($vars){
  $team_name = array_shift($vars);
  $team_players = array_shift($vars);
  $team_players_output = '';
  
  if(is_array($team_players)){
    foreach($team_players as $player){
      $nids[] = $player['nid'];
    }
    
    $player_nodes = node_load_multiple($nids);
    foreach($nids as $nid){
      $lang = $player_nodes[$nid]->language;
      $team_players_output .= '<div class="squad-player">';
      $position_term = taxonomy_term_load($player_nodes[$nid]->field_person_role[$lang][0]['tid']);
      $team_players_output .= '<div style="width:25px; float: left;">'.$player_nodes[$nid]->field_person_number[$lang][0]['value'].'. </div>'; 
      $team_players_output .= '<div>'.l($player_nodes[$nid]->title, 'node/'.$nid).' <span style="float: right;">'.$position_term->field_role_short_name[array_shift(array_keys($position_term->field_role_short_name))][0]['safe_value'].'</span></div>'; 
      //$team_players_output .=  '<div style="float:right">'.theme('image_style', array( 'path' =>  $player_nodes[$nid]->field_person_photo[$lang][0]['uri'], 'style_name' => 'squad_player_thumbnail')).'</div>'; 
      $team_players_output .= '</div>';
    }
  }
  else
    $team_players_output = $team_players;
  
  $output = '';
  
  $output = '
  <div class="team-block">
    <h2>' . $team_name . '</h2>
    <div class="team-players">' . $team_players_output . '</div>
  </div>';
  
  return $output;
}

function custom_match_block_view_alter(&$data, $block){
  if($block->module == 'views' && $block->delta == 'matches-next_match')
    $data['subject'] = '<a href="#" id="next-match-link">'.$data['subject'] .'</a>';
}
?>