<?php

function custom_match_menu(){
  $items = array();
  
  $items['get_next_match_ajax/%']= array(
    'type'=>MENU_CALLBACK,
    'page callback'=>'_get_next_match',
    'page arguments'=>array(1),
    'access callback' => TRUE
  );
  
  $items['get_prev_match_ajax/%']= array(
    'type'=>MENU_CALLBACK,
    'page callback'=>'_get_prev_match',
    'page arguments'=>array(1),
    'access callback' => TRUE
  );
  
  return $items;
}

function custom_match_theme(){
  return array(
  'custom_match_arsenal_logo_match_block'=> array(),
  'custom_match_simple_tabs'=> array('variables'=>array()),
  'custom_match_match_teaser'=> array('variables'=>array()),
  'custom_match_match_goals'=> array('variables'=>array()),
  'custom_match_match_team_block'=> array('variables'=>array()),
  );
}

function custom_match_preprocess_node(&$vars){
  $node = $vars['node'];
  if($node->type == 'match'){
    $view = views_get_view('matches');
    $view->set_display('match_events');
    $view->set_arguments(array($node->nid));
    $view->execute('match_events');

    $arsenal_events = array();
    if(!empty($view->result)){
      foreach($view->result as $event_row){
        $_player_nid = $event_row->field_field_match_events[0]['rendered']['entity']['field_collection_item'][$event_row->field_field_match_events[0]['raw']['value']]['field_match_event_player']['#items'][0]['nid'];
        $event_type = $event_row->field_field_match_events[0]['rendered']['entity']['field_collection_item'][$event_row->field_field_match_events[0]['raw']['value']]['field_match_event_event_type']['#items'][0]['tid'];
        $event_minute = $event_row->field_field_match_events[0]['rendered']['entity']['field_collection_item'][$event_row->field_field_match_events[0]['raw']['value']]['field_match_event_minute']['#items'][0]['safe_value'];
        
        $arsenal_events[$_player_nid][] = array('player'=>node_load($_player_nid), 'event_type'=>taxonomy_term_load($event_type), 'event_minute'=>$event_minute);
        uasort($arsenal_events[$_player_nid],'_sort_events');
      }    
      $vars['node']->arsenal_events  = $arsenal_events;
  
      $view = views_get_view('matches');
      $view->set_display('match_events_opponent');
      $view->set_arguments(array($node->nid));
      $view->execute('match_events_opponent');

      $opponent_events = array();
      $event_types = array();
      foreach($view->result as $event_row){
        $_player_name = $event_row->field_field_match_events_opponent[0]['rendered']['entity']['field_collection_item'][$event_row->field_field_match_events_opponent[0]['raw']['value']]['field_match_event_opp_player']['#items'][0]['safe_value'];
        $event_type = $event_row->field_field_match_events_opponent[0]['rendered']['entity']['field_collection_item'][$event_row->field_field_match_events_opponent[0]['raw']['value']]['field_match_event_opp_event_type']['#items'][0]['tid'];
        $event_minute = $event_row->field_field_match_events_opponent[0]['rendered']['entity']['field_collection_item'][$event_row->field_field_match_events_opponent[0]['raw']['value']]['field_match_event_opp_minute']['#items'][0]['safe_value'];
        
        $opponent_events[$_player_name][] = array('player'=>$_player_name, 'event_type'=>taxonomy_term_load($event_type), 'event_minute'=>$event_minute);
        uasort($opponent_events[$_player_name],'_sort_events');
      }
      
      $vars['node']->opponent_events = $opponent_events;  
      //$vars['connected_news'] = views_embed_view('news','match_news');
    }
    $news_view = views_get_view('news');
    $news_view->set_display('match_news');
    $news_view->set_arguments(array(arg(1)));
    $vars['connected_news'] = $news_view->render('match_news');
    $vars['next_match_link'] = '';
    $vars['prev_match_link'] = '';
    $next_match_nid = _get_next_match_nid($node->nid);
    if(!empty($next_match_nid))
      $vars['next_match_link'] = l(t('Next match'),'node/'.$next_match_nid,array('attributes'=>array('id'=>'match-page-next-match-link')));
    $prev_match_link = _get_prev_match_nid($node->nid);
    if(!empty($prev_match_link))
      $vars['prev_match_link'] = l(t('Previous match'),'node/'.$prev_match_link,array('attributes'=>array('id'=>'match-page-prev-match-link')));  
  }
  if($node->type == 'matches_archive'){
    drupal_add_js(drupal_get_path('module', 'custom_match') . '/misc/archive_matches.js'); 
    $view = views_get_view('matches');
    $view->set_display('season_matches');
    $view->set_arguments(array(arg(1)));
    $view->execute('season_matches');
    if(!empty($view->result)){
      $header = array(
        array('data'=>t('Match'),'style'=>'width: 600px;'),
        array('data'=>t('Result'),'style'=>'width: 10px;'),
        t('Date'),
        t('Tournament'),
        t('Round'));
      
      foreach($view->result as $row){
        $fields = $row->field_field_archive_match[0]['rendered']['entity']['field_collection_item'][$row->field_data_field_archive_match_field_archive_match_value];
        
        $title = ($fields['field_archive_match_place']['#items'][0]['value'] == 'away' ? '{OPP} - {ARS}' : '{ARS} - {OPP}');
        $title = str_replace(array('{ARS}','{OPP}'),array(t('Arsenal'),$fields['field_archive_match_opponent'][0]['#title']),$title);
        $rows[$row->field_data_field_archive_match_field_archive_match_value] = array(
          (!empty($fields['field_archive_match_squad_ars']) || !empty($fields['field_archive_match_squad_opp']) || !empty($fields['field_archive_match_events']) ?          
            l($title,'',array('attributes'=>array('class'=>'archive-match-title','id'=>'archive-match-'.$row->field_data_field_archive_match_field_archive_match_value))).
            '<div style="display: none;" class="archive-match-events" id="match-events-'.$row->field_data_field_archive_match_field_archive_match_value.'">'
            .(!empty($fields['field_archive_match_squad_ars']) ? '<b>'.t('Arsenal squad').'</b>: '.nl2br($fields['field_archive_match_squad_ars'][0]['#markup']).'<br />' : '')
            .(!empty($fields['field_archive_match_squad_opp']) ? '<b>'.t('Opponent squad').'</b>: '.nl2br($fields['field_archive_match_squad_opp'][0]['#markup']).'<br />' : '')
            .(!empty($fields['field_archive_match_events']) ? '<b>'.t('Match events').':</b><br />'.nl2br($fields['field_archive_match_events'][0]['#markup']): '')
            .'</div>'
          : $title)
          ,
          $fields['field_archive_match_result'][0]['#markup'],
          $fields['field_archive_match_date'][0]['#markup'],
          $fields['field_archive_match_tournament'][0]['#title'],
          $fields['field_archive_match_round'][0]['#markup'],
        );
      }
      $table = array('#theme'=>'table','#header'=>$header, '#rows'=>$rows); 
      $vars['season_matches'] = render($table);
    }
    //$vars['season_matches'] = $view->render('season_matches');
    
  }
}

function custom_match_form_alter(&$form, $form_state, $form_id){
  if($form_id == 'match_node_form'){
    drupal_add_js(drupal_get_path('module', 'custom_match') . '/misc/arsenal_squad.js');
    drupal_add_css(drupal_get_path('module', 'custom_match') . '/misc/styles.css');
  }
}

function _sort_events($a, $b) 
{
    if ($a['event_minute'] == $b['event_minute']) {
        return 0;
    }
    return ((int)$a['event_minute'] < (int)$b['event_minute']) ? -1 : 1;
}

function _get_next_match_nid($current_id){
  
  if((int)$current_id > 0)
  {
    $current_node = node_load($current_id);
    $next_ids = db_query("
      SELECT sd.entity_id as next_match_id,
            (SELECT sd.entity_id
            FROM {field_data_field_match_start_date} sd
            ORDER BY sd.field_match_start_date_value desc
            LIMIT 1) as last_match_id
      FROM {field_data_field_match_start_date} sd
      WHERE sd.field_match_start_date_value > :start_date 
      ORDER BY sd.field_match_start_date_value
      LIMIT 1 
    ",array(':start_date'=>$current_node->field_match_start_date[$current_node->language][0]['value']))->fetchAssoc();
    if(!empty($next_ids['next_match_id']) && (int)$next_ids['next_match_id'] > 0){
      return $next_ids['next_match_id'];
    }
    else{
      return null;
    }
  }   
}

function _get_next_match($current_id){
  
  if((int)$current_id > 0)
  {
    $current_node = node_load($current_id);
    $next_ids = db_query("
      SELECT sd.entity_id as next_match_id,
            (SELECT sd.entity_id
            FROM {field_data_field_match_start_date} sd
            ORDER BY sd.field_match_start_date_value desc
            LIMIT 1) as last_match_id
      FROM {field_data_field_match_start_date} sd
      WHERE sd.field_match_start_date_value > :start_date 
      ORDER BY sd.field_match_start_date_value
      LIMIT 1 
    ",array(':start_date'=>$current_node->field_match_start_date[$current_node->language][0]['value']))->fetchAssoc();
    if(!empty($next_ids['next_match_id']) && (int)$next_ids['next_match_id'] > 0){
      $id = $next_ids['next_match_id'];
      $last_id = $next_ids['last_match_id'];
      $message = "OK";
    }
    else{
      $id = $last_id = $current_id;
      $message = "LAST_MATCH";
    }
  }
  else{
    $id = $current_id;
    $message = "WRONG_PARAMETER";
  }
  
  $html = views_embed_view('matches','next_match',$id);
  $data = array('html'=>$html,'id'=>$id,'message'=>$message, 'last_match_id' => $last_id);  
  return drupal_json_output($data);
    
}


function _get_prev_match_nid($current_id){
  
  if((int)$current_id > 0)
  {
    $current_node = node_load($current_id);
    
    $next_ids = db_query("
      SELECT sd.entity_id as prev_match_id,
            (SELECT sd.entity_id
            FROM {field_data_field_match_start_date} sd
            ORDER BY sd.field_match_start_date_value asc
            LIMIT 1) as first_match_id
      FROM {field_data_field_match_start_date} sd
      WHERE sd.field_match_start_date_value < :start_date 
      ORDER BY sd.field_match_start_date_value desc
      LIMIT 1 
    ",array(':start_date'=>$current_node->field_match_start_date[$current_node->language][0]['value']))->fetchAssoc();
    if(!empty($next_ids['prev_match_id']) && (int)$next_ids['prev_match_id'] > 0){
      return $next_ids['prev_match_id'];
    }
    else{
      return null;
    }
  }
}



function _get_prev_match($current_id){
  
  if((int)$current_id > 0)
  {
    $current_node = node_load($current_id);
    
    $next_ids = db_query("
      SELECT sd.entity_id as prev_match_id,
            (SELECT sd.entity_id
            FROM {field_data_field_match_start_date} sd
            ORDER BY sd.field_match_start_date_value asc
            LIMIT 1) as first_match_id
      FROM {field_data_field_match_start_date} sd
      WHERE sd.field_match_start_date_value < :start_date 
      ORDER BY sd.field_match_start_date_value desc
      LIMIT 1 
    ",array(':start_date'=>$current_node->field_match_start_date[$current_node->language][0]['value']))->fetchAssoc();
    if(!empty($next_ids['prev_match_id']) && (int)$next_ids['prev_match_id'] > 0){
      $id = $next_ids['prev_match_id'];
      $last_id = $next_ids['first_match_id'];
      $message = "OK";
    }
    else{
      $id = $current_id;
      $message = "FIRST_MATCH";
    }
  }
  else{
    $id = $current_id;
    $message = "WRONG_PARAMETER";
  }
  $html = views_embed_view('matches','next_match',$id);
  $data = array('html'=>$html,'id'=>$id,'message'=>$message, 'first_match_id'=>$last_id);  
  return drupal_json_output($data);
    
}

function custom_match_preprocess_block(&$vars){
  $block = $vars['block'];       
  if($block->delta == 'matches-next_match' && $block->module == 'views'){   
    $block->subject = '<span class="next-prev-wrapper"><a href="#" id="prev-match-link" class="Prev">&nbsp;</a>&nbsp;</span>'.$block->subject.'<span class="next-prev-wrapper"><a href="#" id="next-match-link" class="Next">&nbsp;</a></span>';    
  } 
}

function theme_custom_match_arsenal_logo_match_block(){
  $image_uri = 'arsenal_logo_small.gif';  
  //$image_uri = drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme')).'/img/arsenal_logo_small.gif';  
//  die($image_uri);
  return theme('image_style', array('style_name' => 'team_logo_small', 'path' => $image_uri));
  //return theme('image', $path . '/' . FILENAME_ARSENAL_EMBLEM);
}

function custom_match_preprocess_views_view_fields(&$variables){
  $view = $variables['view'];
  if($view->name == 'matches' && $view->current_display == 'next_match'){
    if($view->result[0]->field_field_match_place[0]['raw']['value'] == 'away'){
      $first_team_img = render($variables['fields']['field_team_logo']->content); 
      $first_team_name = render($variables['fields']['field_match_opponent']->content); 
      $second_team_img = theme('custom_match_arsenal_logo_match_block');
      $second_team_name = t('Arsenal');
    }
    else{
      $first_team_img = theme('custom_match_arsenal_logo_match_block');
      $first_team_name = t('Arsenal');
      $second_team_img = render($variables['fields']['field_team_logo']->content); 
      $second_team_name = render($variables['fields']['field_match_opponent']->content); 
    }
    $variables['match']['teams']['first'] = array('img'=>$first_team_img, 'name'=>$first_team_name);
    $variables['match']['teams']['second'] = array('img'=>$second_team_img, 'name'=>$second_team_name);
    $month_names_genitive = variable_get('month_names_genitive',array());
    $match_timestamp = strtotime($view->result[0]->field_field_match_start_date[0]['raw']['value']) + date('Z');
    $month = date('m',$match_timestamp);
    
    $variables['match']['start_date'] =  format_date($match_timestamp,'custom','l, j ').(isset($month_names_genitive[$month]) ? $month_names_genitive[$month]  : date('F',$match_timestamp)).date(' H:i',$match_timestamp);
    
    $variables['match']['score'] = '';
    if(!empty($variables['fields']['field_match_result'])){
      $variables['match']['score'] = render($variables['fields']['field_match_result']->content);
    }
    
    $variables['additional_link'] = '';
    if(strtotime($view->result[0]->field_data_field_match_start_date_field_match_start_date_val) > time())
      $variables['additional_link'] = l('<span class="livetv-link">'.t('Online').'</span>','http://www.liveresult.ru/football/txt/team/arsenal',array('html'=>true, 'attributes'=>array('target'=>'_blank','class'=>'Online'),'absolute'=>TRUE));
    
    
    $livetv_arsenal_matches = _custom_match_get_livetv_arsenal_matches();  
    foreach($livetv_arsenal_matches as $_livetv_match){
      if(date('d/m/Y',$match_timestamp) == date('d/m/Y', $_livetv_match['timestamp']))
        $variables['additional_link'] .= l('<span class="livetv-link">LiveTV</span>',$_livetv_match['url'],array('external'=>TRUE,'html'=>true, 'attributes'=>array('target'=>'_blank')));  
      
    }
  }  
}

  
function _tab_divs($tabs, $div_css = '', $selected_number = 0, $css_suffix = '') {
  $html = "<div class='$div_css'>";
  if (is_array($tabs)) {  
    foreach ($tabs as $k=>$e) {
      $selected = ($selected_number == $k) ? 'tab-active' : '';
      $id = $k.$css_suffix;
      $html .= "<div id='$id' class='tab $selected'>$e</div>";
    }
  }
  $html .=  '<div class="cf"></div>'.
            '</div>';
  return $html;
}

function theme_custom_match_simple_tabs( $vars ) {   
  $headers = array_shift($vars);
  $content = array_shift($vars);
  $selected_number = array_shift($vars);
  
  $path = drupal_get_path('theme', variable_get('theme_default','fc_arsenal_theme'));
  drupal_add_js($path . '/js/custom.js');
  $html = '<div class="tabs">';
  if (is_array($headers)) {
    $html .= _tab_divs($headers, "header", $selected_number);
  }
  if (is_array($content)) {
    $html .= _tab_divs($content, "content", $selected_number, "content");
  }
  
  $html .= '</div>';
  return $html;
}

function theme_custom_match_match_teaser($vars=array()){
  $node = array_shift($vars);
  $title = array_shift($vars);
  $output = '';
  //dd($node);
  $output .= '<div class="match-teaser">';
  //$output .= '<h2>'. (($title != '') ? $title : $node->title ) . '</h2>';
  $output .= '<h2>'.ucfirst(t('Match-centre')).'</h2>';
  
  $rival_nid = $node->field_match_opponent[$node->language][0]['nid'];
  $rival_node = node_load($rival_nid);
  if($rival_node->field_team_logo[$rival_node->language][0]['fid']){
    $rival_emblem = theme_image(array('attributes'=>array(), 'path'=> $rival_node->field_team_logo[$rival_node->language][0]['uri']));
  } else {
    $path = drupal_get_path('theme', variable_get('theme_default','fc_arsenal_theme'));
    $image_path = $path . '/no-photo.jpg';
    $rival_emblem = theme('image', array('attributes'=>array(), 'path'=>$image_path));
  }
  $arsenal_emblem = theme('custom_match_arsenal_logo_match_block');
  
  $rival_block = '
      <div class="team-block">
        <div class="emblems-line">'.$rival_emblem.'</div>
      </div>';
  $arsenal_block = '
      <div class="team-block">
        <div class="emblems-line">'.$arsenal_emblem.'</div>
      </div>';
  
  $result = '';
  if(!empty($node->field_match_result)) 
    $result = $node->field_match_result[$node->language][0]['safe_value'];
  
 /* foreach($node->arsenal_events as $player=>$events){
    foreach($events as $event){
      if(isset($event['event_type']->field_match_event_type_code['und'][0]['value']) && ($event['event_type']->field_match_event_type_code['und'][0]['value'] == 'goal' || $event['event_type']->field_match_event_type_code['und'][0]['value'] == 'penalty_goal')) {
        
        $goals[$event['player']->title][] = $event; //[$event['player']->title][] = $event['event_minute'];
        $goals_sort[] = $event; //[$event['player']->title][] = $event['event_minute'];
      }
    }
  }
  
  uasort($goals_sort,'_sort_events');
  $arsenal_goals_str = '';
  foreach($goals_sort as $_goals){
    if(!isset($goals[$_goals['player']->title]))
      continue;
      $arsenal_goals_str .= $_goals['player']->title;
    foreach($goals[$_goals['player']->title] as $_player_goals){
     // foreach($_player_goals as $_player_goal){
     // var_dump($_player_goal);
        $goals_str.= ', '.$_player_goals['event_minute'];  
      //}
    }
    unset($goals[$_goals['player']->title]);
    $arsenal_goals_str.= '; ';
  }
  
  foreach($node->opponent_events as $player=>$events){
    foreach($events as $event){
      if(isset($event['event_type']->field_match_event_type_code['und'][0]['value']) && ($event['event_type']->field_match_event_type_code['und'][0]['value'] == 'goal' || $event['event_type']->field_match_event_type_code['und'][0]['value'] == 'penalty_goal')) {
        
        $goals[$event['player']][] = $event; //[$event['player']->title][] = $event['event_minute'];
        $goals_sort[] = $event; //[$event['player']->title][] = $event['event_minute'];
      }
    }
  }
  
  uasort($goals_sort,'_sort_events');
  $opponent_goals_str = '';
  foreach($goals_sort as $_goals){
    if(!isset($goals[$_goals['player']]))
      continue;
      $opponent_goals_str .= $_goals['player']->title;
    foreach($goals[$_goals['player']] as $_player_goals){
     // foreach($_player_goals as $_player_goal){
     // var_dump($_player_goal);
        $goals_str.= ', '.$_player_goals['event_minute'];  
      //}
    }
    unset($goals[$_goals['player']->title]);
    $opponent_goals_str.= '; ';
  }
  
   print_r($opponent_goals_str);
  */
  if($node->field_match_place[$rival_node->language][0]['value'] == 'away'){
    $teaser_left = '<div class="players">'.$rival_block . '<div class="vs">VS</div>' . $arsenal_block . '<div class="cf">&nbsp;</div></div>';
    $teaser_right = '
    <div class="team-line">
      <div class="match-centre-team">
        <div class="match-centre-team-name">'.$rival_node->title.'</div>
        <div class="match-centre-goals">'.theme('custom_match_match_goals',array($node,'opponent')).'</div>
      </div>
      <div class="match-centre-match-result">'.$result.'</div> '.'
      <div class="match-centre-team">
        <div class="match-centre-team-name">'.t('Arsenal').'</div>
        <div class="match-centre-goals">'.theme('custom_match_match_goals',array($node,'arsenal')).'</div>
      </div>
    </div>';
  } else {
    $teaser_left = '<div class="players">'.$arsenal_block . '<div class="vs">VS</div>' . $rival_block . '<div class="cf">&nbsp;</div></div>';
    $teaser_right = '
    <div class="team-line">
      <div class="match-centre-team">
        <div class="match-centre-team-name">'.t('Arsenal').'</div>
        <div class="match-centre-goals">'.theme('custom_match_match_goals',array($node,'arsenal')).'</div>
      </div>
      <div class="match-centre-match-result">'.$result.'</div> '.'
      <div class="match-centre-team">
        <div class="match-centre-team-name">'.$rival_node->title.'</div>
        <div class="match-centre-goals">'.theme('custom_match_match_goals',array($node,'opponent')).'</div>
      </div>
    </div>';
  }
  
  $additional_info = '<div class="match-info-left">';
  
  
  if(!empty($node->field_match_start_date) && $node->field_match_start_date[$node->language][0]['value']){
    $additional_info .= '
    <div class="info  match-date">
      <span class="label">'.t('Date').': </span>
      <span class="value">'.format_date(strtotime($node->field_match_start_date[$node->language][0]['value']) + date('Z'),'custom','m.d.Y').'</span>
    </div>';
  }
  
  if(!empty($node->field_match_season) && $node->field_match_season[$node->language][0]['taxonomy_term']){
    $additional_info .= '
    <div class="info  match-season">
      <span class="label">'.t('Season').': </span>
      <span class="value">'.$node->field_match_season[$node->language][0]['taxonomy_term']->name.'</span>
    </div>';
  }
  
   if(!empty($node->field_match_round) && $node->field_match_round[$node->language][0]['value']){
    $additional_info .= '
    <div class="info match-round">
      <span class="label">'.t('Tournament round').': </span>
      <span class="value">'.$node->field_match_round[$node->language][0]['value'].'</span>
    </div>';
  }
  
  $additional_info.='</div><div class="match-info-right">';
  
  if(!empty($node->field_match_referee) && $node->field_match_referee[$node->language][0]['node']){
    $additional_info .= '
    <div class="info match-referee">
      <span class="label">'.t('Referee').': </span>
      <span class="value">'.$node->field_match_referee[$node->language][0]['node']->title.'</span>
    </div>';
  }
  
    if(!empty($node->field_match_stadium) && $node->field_match_stadium[$node->language][0]['node']){
    $additional_info .= '
    <div class="info match-stadium">
      <span class="label">'.t('Stadium').': </span>
      <span class="value">'.$node->field_match_stadium[$node->language][0]['node']->title.'</span>
    </div>';
  }
  
  if(!empty($node->field_match_attendance) && $node->field_match_attendance[$node->language][0]['value']){
    $additional_info .= '
    <div class="info match-attendance">
      <span class="label">'.t('Attendance').': </span>
      <span class="value">'.number_format($node->field_match_attendance[$node->language][0]['value'],0,'',' ').'</span>
    </div>';
  }
  
   $additional_info .= '</div>';
  
 /* if($node->field_goal_authors[0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">Авторы голов: </span>
      <span class="value">'.$node->field_goal_authors[0]['view'].'</span>
    </div>';
  }
  
  if($node->field_additional_information_0[0]['value']){
    $additional_info .= '
    <div class="info">
      <span class="label">Дополнительная информация: </span>
      <span class="value">'.$node->field_additional_information_0[0]['view'].'</span>
    </div>';
  }
      */
  //dd($node);
  
  if(!empty($node->field_match_gallery) && $node->field_match_gallery[$node->language][0]['node']){
    $additional_info .= '
    <div class="info">
      <span class="value">'.l(t('Gallery') , 'node/'.$node->field_match_gallery[$node->language][0]['node']->nid).'</span>
    </div>';
  }
  
  $output .= '
<div class="teaser-content">
  <div class="teaser-left-part">
    '.$teaser_left.'
  </div>
  <div class="teaser-right-part">
    '.$teaser_right.'
    <div class="tournament">'.$node->field_match_tournament[$node->language][0]['taxonomy_term']->name.'</div>
  </div>
  <div class="cf">&nbsp;</div>
  <div class="additional-info">'.$additional_info.'</div>
</div>';
  //$node;
  
  $output .= '</div>';
  
  return $output;
}

function theme_custom_match_match_team_block($vars){
  $team_name = array_shift($vars);
  $team_players = array_shift($vars);
  $match_events = array_shift($vars);
  $team_players_output = '';
  $i=0;
  
  if(is_array($team_players)){
    foreach($team_players as $player){
      $nids[] = $player['nid'];
    }
    
    $subs = (array_diff(array_keys($match_events), $nids));
    foreach($subs as $sub){
      $nids[] = $sub;
    }
    
    /*foreach($match_events as $_events){
    array_merge()
      foreach()
      
    print_r($_event['event_type']);*/
      /*if(isset($_event['event_type']->field_match_event_type_code['und'][0]['value']) && $_event['event_type']->field_match_event_type_icon['und'][0]['value'] == 'sub_in')
      {        die();
        $nids[] = $_event['event_player']->nid;  
      } */
    //}
    
    $player_nodes = node_load_multiple($nids);
    
    foreach($nids as $nid){
      $i++;
      $lang = $player_nodes[$nid]->language;
      $team_players_output .= '<div class="squad-player '.($i%2 == 0 ? 'squad-player-odd' : 'squad-player-even').'">';
      $position_term = taxonomy_term_load($player_nodes[$nid]->field_person_role[$lang][0]['tid']);
      //$team_players_output .= '<div style="width:25px; float: left;">'.$player_nodes[$nid]->field_person_number[$lang][0]['value'].'. </div>'; 
      $team_players_output .= '<div style="float: left;" '.($i > 11 ? 'class="squad-player-subs"' : '').'>'.l($player_nodes[$nid]->title, 'node/'.$nid).'</div>';
      
      if(isset($match_events[$nid])){   
        foreach($match_events[$nid] as $event){
          $event_icon = theme_image(array('path'=>$event['event_type']->field_match_event_type_icon['und'][0]['uri'], 'attributes'=>array('title'=>'('.strtolower($event['event_type']->name).', '.$event['event_minute'].' '.t('min').')', )));
          $team_players_output .=' <div style="float: left; margin-left: 3px;">'.$event_icon.' <span style="font-size: 10px;">'.$event['event_minute'].'\'</span></div>';  
        }
      }
      //$team_players_output .=' <span style="float: right;">'.$position_term->field_role_short_name[array_shift(array_keys($position_term->field_role_short_name))][0]['safe_value'].'</span></div>'; 
      //$team_players_output .=  '<div style="float:right">'.theme('image_style', array( 'path' =>  $player_nodes[$nid]->field_person_photo[$lang][0]['uri'], 'style_name' => 'squad_player_thumbnail')).'</div>'; 
      $team_players_output .= '<div class="cf" style="padding:0px;"></div></div>';
      if($i == 11){
        $team_players_output .= '<div class="squad-player squad-subs">'.t('Substitutes').'</div>';
      }
    }
  }
  else{
    $players_array = explode("\n", trim($team_players));
    
    foreach($players_array as $_player) {
      $i++;
      $_player = trim($_player);
      if(empty($_player)) continue;
      //$f = array_shift($match_events);
      //var_dump($f[0]['player']);
      $team_players_output .= '<div class="squad-player '.($i%2 == 0 ? 'squad-player-odd' : 'squad-player-even').'">';
      $team_players_output .= '<div style="float: left;" '.($i > 11 ? 'class="squad-player-subs"' : '').'>'.$_player.'</div>';
      if(isset($match_events[$_player])){   
        foreach($match_events[$_player] as $event){ 
          $event_icon = theme_image(array('path'=>$event['event_type']->field_match_event_type_icon['und'][0]['uri'], 'attributes'=>array('title'=>'('.strtolower($event['event_type']->name).', '.$event['event_minute'].' '.t('min').')', )));
          $team_players_output .=' <div style="float: left; margin-left: 3px;">'.$event_icon.' <span style="font-size: 10px;">'.$event['event_minute'].'\'</span></div>';  
        }
      }
      
      $team_players_output .= '<div class="cf" style="padding:0px;"></div></div>'; 
      if($i == 11){
        $team_players_output .= '<div class="squad-player squad-subs">'.t('Substitutes').'</div>';
      }
    }
    
  }
  
  $output = '';
  
  $output = '
  <div class="team-block '.($team_name == t('Arsenal') ? 'team-block-arsenal' : '').'">
    <h2><span class="team-block-team-name '.($team_name == t('Arsenal') ? ' team-blockteam-name-arsenal' : '').'">' . $team_name . '</span></h2>
    <div class="team-players">' . $team_players_output . '</div>
  </div>';
  
  return $output;
}


function _custom_match_get_livetv_arsenal_matches(){

  $last_sync = variable_get('livetv_last_sync_date',0);
  $arsenal_matches = variable_get('livetv_arsenal_matches',null);
  if(empty($last_sync) || ((time() - $last_sync) > 60*60*24*1) || $arsenal_matches == null){
    $rss_data = _custom_news_get_rss_data('http://img.livetv.ru/rss/upcoming_ru.xml'); 
    $arsenal_matches = array();
    foreach($rss_data['items'] as $_item){
      if(strpos($_item['guid'],'arsenal') !== false && strpos($_item['title'],iconv('CP1251','UTF-8','Арсенал Л')) !== false ){
        $arsenal_matches[$_item['timestamp']] = $_item;
      }
    }
    variable_set('livetv_last_sync_date',time());
    variable_set('livetv_arsenal_matches',$arsenal_matches);
  }
  return $arsenal_matches;
}

function custom_match_views_post_render(&$view, &$output) {
  if($view->name == 'matches' && $view->current_display == 'calendar'){
   
    //dpm($view); 
  }
    

}

/*function custom_match_block_view_alter(&$data, $block){
  if($block->module == 'views' && $block->delta == 'matches-next_match')
  {
    //$img_path = drupal_get_path('theme',variable_get('theme_default','fc_arsenal_theme'));
    //$data['subject'] = '<span class="next-prev-wrapper"><a href="#" id="prev-match-link" class="Prev">&nbsp;</a>&nbsp;</span>'.$data['subject'].'<span class="next-prev-wrapper"><a href="#" id="next-match-link" class="Next">&nbsp;</a></span>';
  }
} */

function theme_custom_match_match_goals($vars){  
  $node = array_shift($vars);
  $goals_team = array_shift($vars);
  
  
  
  if($goals_team == 'arsenal'){
    $field = 'arsenal_events';
    $opp_field = 'opponent_events';
  }
  else{
    $field = 'opponent_events';
    $opp_field = 'arsenal_events';
  }
  
  static $tids = array();
  static $penalty_tid = 0;
  static $og_tid = 0;
  
  if(empty($tids)){
    $vocab = taxonomy_vocabulary_machine_name_load('match_event_type');
    $terms = taxonomy_get_tree($vocab->vid);
    foreach($terms as $term)
      $tids[] = $term->tid;
    $terms = taxonomy_term_load_multiple($tids);
    $tids = array();
    foreach($terms as $term){
      if(!empty($term->field_match_event_type_code)){
        $type = array_shift(array_shift($term->field_match_event_type_code));
        if($type['value'] == 'goal' || $type['value'] == 'penalty_goal'){
          $tids[$term->tid] = $term->tid; 
          if($type['value'] == 'penalty_goal')
            $penalty_tid = $term->tid;
        }
        if($type['value'] == 'own_goal')
          $og_tid = $term->tid;  
      }
    }
  }
  $team_goals = array();
  $team_goals_html = '';
 
  if(isset($node->{$field}) || isset($node->{$opp_field})){
    foreach($node->{$field} as $player){ 
      foreach($player as $event){
        if(!empty($tids) && in_array($event['event_type']->tid,$tids)){   
          $team_goals[$event['event_minute']] = ($event['event_type']->tid == $penalty_tid ? '('.t('pen.').')' : '').($goals_team == 'arsenal' ?  $event['player']->title : $event['player']); 
        }
      }
    } 
    
    foreach($node->{$opp_field} as $player){ 
      foreach($player as $event){
        if($event['event_type']->tid == $og_tid){   
          $team_goals[$event['event_minute']] = ' ('.t('o.g.').') '. ($goals_team == 'arsenal' ?  $event['player'] : $event['player']->title); 
        }
      }
    }
    
    
    /*foreach($node->{$opp_field} as $player){ 
      foreach($player as $event){
        if(!empty($og_tid) || !empty($event['event_type']->field_match_event_type_code)){
          if(!empty($event['event_type']->field_match_event_type_code)){
            $type = array_shift(array_shift($event['event_type']->field_match_event_type_code));
            if($type['value'] == 'own_goal')
              $og_tid = $event['event_type']->tid;
          }
          if(!empty($og_tid) && $event['event_type']->tid == $og_tid){   
            $team_goals[$event['event_minute']] = ' ('.t('o.g.').') '. ($goals_team == 'arsenal' ?  $event['player'] : $event['player']->title); 
          }
        }
      }
    }  */    
    ksort($team_goals);
    foreach($team_goals as $min=>$player){
      $team_goals_html .= $min."' ".$player.'<br />';  
    }
  }
  
  
  
  return $team_goals_html; 
}

function custom_match_node_update($node){
  if($node->type == 'match')
    cache_set('stats:players_stats','');
}

function custom_match_node_insert($node){
  if($node->type == 'match')
    cache_set('stats:players_stats','');

}


?>