<?php

function custom_news_node_view($node, $view_mode, $language){
  //$node = $vars['node'];
  if($node->type == 'news'){
    $node->content['news_block'] = views_embed_view('news','block_1');
    $node->content['field_news_tags'] = taxonomy_field_formatter_view('node',$node,'field_news_tags',null,'',$node->field_news_tags[$node->language],array('type'=>'taxonomy_term_reference_link'));
    foreach($node->content['field_news_tags'] as $index=>$item) {
      if($index > 0)
        $node->content['field_news_tags'][$index]['#prefix'] = ', ';  
    }
    if(isset($node->field_news_source) && count($node->field_news_source) > 0)
      $node->content['field_news_source'] = text_field_formatter_view('node',$node,'field_news_source',null,$node->language,$node->field_news_source[$node->language],array('type'=>'text_plain'));
    else   
      $node->content['field_news_source'] = null;
    $node->author = $node->name;
    $node->posted_date = format_date($node->created, 'short', '', date_default_timezone(TRUE), $language);
  } 
}

function custom_news_node_load($nodes, $types){
  foreach($nodes as $nid=>$node){
    if($node->type == 'news'){
      $read_count = db_select('node_counter', 'nc')
                          ->fields('nc', array('totalcount'))
                          ->condition('nid',$nid)
                          ->execute()
                          ->fetchAssoc();
      $nodes[$nid]->read_count =  (int)$read_count['totalcount'];         
    }
  }
}

function custom_news_comment_view($comment, $view_mode, $langcode){
    $comment->content['posted_date'] = format_date($comment->created, 'short', '', date_default_timezone(TRUE), $langcode);
}


function custom_news_theme(){
  return array(
  'read_news_block'=> array('variables'=>array('node'=>NULL)),
  'custom_news_rss_item'=> array('variables'=>array('item'=>NULL)),
  'custom_news_apl_news_rss'=> array('variables'=>array('data'=>NULL,'items_num'=>10)),
  'custom_news_important_news'=> array('variables'=>array('node'=>NULL)),
  );
}


function custom_news_preprocess_views_view_unformatted(&$vars){
  $view = $vars['view'];
  if($view->name =='news' && $view->current_display=='block_1'){
    $vars['news_teaser_count'] = variable_get('news_teaser_count',5);
    $vars['total_rows'] = count($vars['view']->result);
    
    // Load RSS 
    if(drupal_is_front_page() || variable_get('latest_news_block_rss_show_only_on_frontpage', true) == drupal_is_front_page()){
      $rss_block = '';
      $variables['rss_items_html'] = '';
      $rss_url = variable_get('latest_news_block_rss_url','');
      $rss_items_count =  variable_get('latest_news_block_rss_items_count', 5);
      if(!empty($rss_url)){
      
        $rss_data = _custom_news_get_rss_data($rss_url);
        if($rss_data != null)
        {
          if(isset($rss_data['items']) && is_array($rss_data['items'])){  
            $items_num = count($rss_data['items']);
            $items_html = '<ul>';
            for($i=0; $i < $rss_items_count && $i < $items_num; $i++){
              $item = $rss_data['items'][$i]; 
              $items_html .= theme('custom_news_rss_item', $item);
            }
            $items_html .= '</ul>';
            $vars['rss_items_html'] = $items_html; 
          }
        }
      }
    }
  }
  if($view->name =='news' && $view->current_display=='news_by_category'){
    $vars['page_title'] = '';
    if((int)arg(1) > 0){
      $term = taxonomy_term_load(arg(1));
      $vars['page_title'] = $term->name;
    }
  }
  
}

function theme_custom_news_rss_item($item){
  global $language;
  
  $output = '<li><div class="qrss-item">';
  $output .= '<span class="qrss-date">'.format_date($item['timestamp'], 'custom_news_rss_item', '', date_default_timezone(TRUE), $language->language).'</span> ';
  $output .= l($item['title'],$item['url'],array('attributes'=>array('target'=>'_blank','rel'=>'nofollow')));
  $output .= '</div></li>';
  
  return $output;
}

function theme_custom_news_apl_news_rss($vars){
  $rss_data = $vars['data'];
  $rss_items = $rss_data['items'];
  $rss_items_num = $vars['items_num'];
  $output = '
      <div class="view view-qrss-view">
        <div class="view-content view-content-qrss-view">
          <div class="item-list">
            <ul>
              <li>
                <div class="view-item view-item-qrss-view">
                  <div class="view-field view-data-node-data-field-qrssreader-parsed-field-qrssreader-parsed-value">
                  <div class="item-list">
                    <ul>
                      [ITEMS]
                    </ul>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>';
  
  
  $items_output = '';
  for($i=0; $i < $rss_items_num && $i < count($rss_items); $i++){
    $items_output .= theme_custom_news_rss_item($rss_items[$i]);
  }
  
  return str_replace('[ITEMS]',$items_output,$output);
}

function theme_custom_news_important_news($vars){
  $node = $vars['node'];
  if($node != null){
    $output = '<div class="important-news-wrapper"><h2>'.l($node->title,'node/'.$node->nid).'</h2></div>';
    return $output;
  }
}

function custom_news_block_info(){
  $blocks['apl_news'] = array(
    'info' => t('APL News'),
    'status'=>TRUE,
    'weight'=>0,
    'visibility'=>1,
    'region'=>'left',
    'pages'=>'<front>',
    'cache' => -1,
  );
  
  $blocks['important_news'] = array(
    'info' => t('Important news'),
    'status'=>FALSE,
    'weight'=>0,
    'visibility'=>1,
    'region'=>'content',
    'pages'=>'<front>',
    'cache' => -1,
  );
  
   $blocks['top_news'] = array(
    'info' => t('Top news'),
    'status'=>FALSE,
    'weight'=>0,
    'visibility'=>1,
    'region'=>'content',
    'pages'=>'<front>',
    'cache' => -1,
  );
  return $blocks;
  
}

function custom_news_block_view($delta){
  switch($delta){
    case 'apl_news':
      $rss_url = variable_get('custom_news_apl_news_rss_url','');
      if(!empty($rss_url)){
        $block['subject'] = t('APL News');
        $rss_url = variable_get('custom_news_apl_news_rss_url','');
        $rss_items_num = variable_get('custom_news_apl_news_rss_items_num',10);
        $block['content'] = theme('custom_news_apl_news_rss', array('data' => _custom_news_get_rss_data($rss_url),'items_num'=>$rss_items_num));
        return $block;
      }
      break;
      
    case 'important_news':
       $important_news_nid = variable_get('custom_news_important_news_nid',0); 
       if((int)$important_news_nid > 0){  
        $node = node_load($important_news_nid);
        $block['content'] = theme('custom_news_important_news', array('node'=>$node));
        return $block;
       }
        break; 
        
    case 'top_news':
        $block['content'] = views_embed_view('news','block_2');
        return $block;
        break; 
      
  }

}


function _custom_news_get_rss_data($rss_url){
  drupal_load('module','feeds');
  feeds_include_library('common_syndication_parser.inc','common_syndication_parser');
  feeds_include_library('http_request.inc','http_request');
  $response = http_request_get($rss_url);
  if(!empty($response->data) && $response->status_message == 'OK'){
    $rss_data = common_syndication_parser_parse($response->data);
    return $rss_data;
  }
  else return null;
}

//function custom_news_menu_alter(&$items){dpm($items);}

function custom_news_menu(){
  $vocabulary = taxonomy_vocabulary_machine_name_load('news_category');
  $terms = taxonomy_get_tree($vocabulary->vid);
  // db_select('')
  //dpm($terms);
   $items['news'] = array(
    'title' => t('News'),
    'page callback' => 'drupal_goto',
    'page arguments' => array('news-all/date'),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  ); 
   /* $items['news/archive'] = array(
      'title'=> t('News'),
      'type' => MENU_NORMAL_ITEM,
    );*/ 
  /*foreach($terms as $term){
    $items['news/'.$term->tid] = array(
      'title'=> $term->name,
      'type' => MENU_NORMAL_ITEM,
      'menu'=>'main-menu',
      'page callback' => 'show_news_by_category', 
      'page arguments' => array(1), 
      'access arguments' => array('access content'),
    ); 
  }   */
  //dpm($items);
  //$items['news/']
  return $items;
}
?>
