<?php

function customization_block_info(){
  $blocks['customization_login_block'] = array(
    'info' => t('Login links'),
    'status'=>TRUE,
    'weight'=>0,
    'region'=> 'header',
    'visibility'=>1,
    'cache' => -1,
  );
  
  $blocks['random_article'] = array(
    'info' => t('Random article'),
    'status'=>TRUE,
    'weight'=>0,
    'region'=> 'right',
    'pages'=> '<front>',
    'visibility'=>1,
    'cache' => -1,
  );
  
  return $blocks;
}

function customization_block_info_alter(&$blocks, $theme, $code_blocks){
  if(isset($blocks['nodeblock'])){
    $nids = array_keys($blocks['nodeblock']);
    $nodes = node_load_multiple($nids);
    foreach($nodes as $node){
      if($node->type == 'banner' && strtotime($node->field_banner_end_date[$node->language][0]['value'].' +1 day') < time() && $node->status ==1){
        $node->status = 0;
        node_save($node);
     }
    }
  }
}

function customization_block_list_alter(&$blocks){
  $nids = array();
  foreach($blocks as $block)
    if($block->module == 'nodeblock')
      $nids[$block->delta] = $block->bid;
  if(!empty($nids)){
    $nodes = node_load_multiple(array_keys($nids));
    foreach($nodes as $node){
      if($node->type == 'banner' && !(strtotime($node->field_banner_start_date[$node->language][0]['value']) < time() &&
         ((isset($node->field_banner_end_date[$node->language][0]['value']) && $node->field_banner_end_date[$node->language][0]['value'] != null && strtotime($node->field_banner_end_date[$node->language][0]['value'].' +1 day') > time())
          || !isset($node->field_banner_end_date[$node->language][0]['value']) 
          || $node->field_banner_end_date[$node->language][0]['value'] == null)
          )){
              unset($blocks[$nids[$node->nid]]);
        }
       }
  }
}

function customization_theme(){
  return array(
  'customization_login_block'=> array(),
  'customization_content_banner'=> array('variables'=>array('node'=>NULL)),
  'customization_arsenal_logo_match_block'=> array(),
  'customization_simple_tabs'=> array('variables'=>array()),
  'customization_match_teaser'=> array('variables'=>array()),
  'customization_match_team_block'=> array('variables'=>array()),
  );
}
  
function customization_block_view($delta){
  switch($delta){
    case 'customization_login_block':
      $block['content'] = theme('customization_login_block');
      return $block;
      break;
        
    case 'random_article':
      $block['content'] = views_embed_view('random_article','block');
      return $block;
        break;    
  }
}

function theme_customization_content_banner($vars){
  $node = $vars['node'];
  
}    
function theme_customization_login_block(){
  $output = '<div id="block-custom-0" class="block block-custom">
        <div class="content">
            <ul class="LoginLinks">';
  if(user_is_logged_in()){
    global $user;
    $output .= '<li>'.l($user->name,'user/'.$user->uid).'</li><li> | </li><li>'.l(t("Logout"),'logout').'</li>';   
  }
  else{
    $output  .= '<li>'.l(t("Login"),'user').'</li><li> | </li><li>'.l(t("Register"),'user/register').'</li>';
  }
  $output .= '</ul>
        </div>
    </div>';
  return $output;
}

function customization_preprocess_page(&$vars){
  //remove nodes from main page.
  if(drupal_is_front_page())
    unset($vars['page']['content']['system_main']);
}



?>
